name: CI Pipeline

# Trigger the workflow on push to the main branch or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Jobs to run
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 6: Run the Docker container and test
      - name: Run Docker container and test
        run: docker compose up
